### ISSUE TITLE
My (unofficial) Umbraco Archive Processor

### ISSUE THREAD

**Issue by leekelleher** [mikkelhm/ExtractDiff#1]
Hi @mikkelhm, this showed up in my GitHub activity feed - _don't worry, I'm not stalking you._ 😉 

It reminds me of what I've been doing with my (unofficial) [Umbraco Archive repo](http://code.leekelleher.com/umbraco/archive/). I have a console app that grabs the latest Umbraco release does a bunch analysis on it and compares it with the previous release.

It generates various diffs between the 2 versions, outputting HTML, XML, JSON and a zip file.
https://github.com/leekelleher/umbraco-archive-processor/blob/master/src/UmbracoArchiveProcessor/Program.cs#L295

I dump them all on my own archive site, if you want to take a look at the outputs:
http://code.leekelleher.com/umbraco/archive/diffs/

I made a separate library for generating the diffs between zip files:
https://github.com/dotnet-zipdiff-utils/zipdiff

I'm only doing this for the main Umbraco CMS releases, but it could be applied to Deploy, Forms, etc.

If any of this helps? ☺️

**Comment by leekelleher** [comment]
Another interesting project to highlight here too, is [Darren Ferguson's UDiff](https://our.umbraco.com/packages/developer-tools/moriyama-udiff/). It's a console app that you point at a local Umbraco install and it'll compare it with zip of that release, and give you a report.

The idea is that you can see if any core files have been modified, etc.
(This is great when adopting an existing client project, to find any rogue files).

There's a video demo: <https://vimeo.com/65997916>

**Comment by mikkelhm** [comment]
Haha I was thinking about the stalking issue when I saw your message :-)

I should have known that you guys would already have done some thing similar.

This one is, as you might have guessed, beging used for autoupgrades on Umbraco Cloud, where we usually just need a diff package, for at least things like patch upgrades. Its been runing locally, but thought i'd throw it up somewhere public, in case someone could use it. Also for the buildserver to automagically use it, whenever we do a new release (internal or external)

Thanks for commenting as well, Ill check the two repos out for inspiration or usage.

**Comment by leekelleher** [comment]
Cool! 👍

_(I'll close off this "issue")_
